services:
  lecrec:
    image: ghcr.io/professorsam/lecrec:1.0
    ports:
      - "8000:8000"
    volumes:
      - "/mnt/hetznerbox/streams:/streams"
    environment:
      - "LECREC_URLS=${LECREC_URLS}"